Restructure Flavours config

diff --git a/scripts/flav b/scripts/flav
--- a/scripts/flav
+++ b/scripts/flav
@@ -1,12 +1,30 @@
 #!/usr/bin/bash
 
 CONFIG_DIR=~/.config/flavours
+CONFIG="$CONFIG_DIR/config.toml"
+
 CONFIG_HEADER="#WARNING: This file is automatically generated. Do not change it directly"
 
-# generate config
-cat <(echo "$CONFIG_HEADER") \
-    <(echo) \
-    "$CONFIG_DIR"/config.toml.d/* \
-    > "$CONFIG_DIR/config.toml" 2> /dev/null
+# Check that the previous config was generated by this script
+if [ "$(head -1 "$CONFIG")" != "$CONFIG_HEADER" ]; then
+    echo "The current config '$CONFIG' was not generated by this script. Aborting."
+    exit 1
+fi
+
+# Generate the config from the '.config.toml.d'
+echo -e "$CONFIG_HEADER\n" > "$CONFIG"
+find "$CONFIG_DIR"/config.toml.d/ -type f,l \
+    | while read file;
+do
+    # If a file mentioned in the subcofnig is missing its basedir, skip the whole subconfig
+    cat "$file" | sed -n 's/^\s*file\s*=\s"\(.*\)"\s*$/\1/p' \
+        | while read subconfig;
+    do
+        if  ! [ -e "$(dirname ${subconfig/#\~/$HOME})" ]; then
+            continue
+        fi
+    done
+    cat "$file" >> "$CONFIG"
+done
 
 ~/.cargo/bin/flavours "$@"
